# auto-merge dependabot
name: auto-merge

on: 
  pull_request:
    branches: 
      - dev

jobs:
  auto-merge:
    timeout-minutes: 5

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: sudo-bot/action-pull-request-merge@v1.1.1
        with:
          github-token: ${{ secrets.GITHUBTOKEN }}  
          merge-method: rebase
          filter-label: automerge
      
